### ISSUE TITLE
Don't show No SRV records found if discovered via .well-known

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/fed-tester-ui#18]
Currently when a server is discovered via .well-known it skips the SRV check which leads people to think their SRV doesn't exist.

Related: https://github.com/matrix-org/matrix-federation-tester/issues/37

**Comment by richvdh** [comment]
> Currently when a server is discovered via .well-known it skips the SRV check

noo, it will do the SRV check on the target of the .well-known.

**Comment by heini** [comment]
But isn't this wrong? I mean, .well-known and the SRV record serve the same purpose, to deliver the name of the real homeserver. So if you get the .well-known file from example.org, it might point you to chat.example.org. The same should be done for the SRV record, then. It should lookup _matrix._tcp.example.org, not _matrix._tcp.chat.example.org, and it should return something like "10 0 8448 chat.example.org".

**Comment by aaronraimist** [comment]
@heini No it isn't wrong. Read https://matrix.org/docs/spec/server_server/r0.1.4#resolving-server-names

**Comment by heini** [comment]
Yes, it is. Read point 4. The SRV record is used if the .well-known results in an error. And that is logical. But using the result of the .well-known lookup to check the SRV record is not. They are equivalent.

**Comment by aaronraimist** [comment]
If .well-known results in an error yes. But when the .well-known does NOT result in an error then see point 3 which is what this issue was about.

I agree that it is confusing and I don't know why it was written this way however it was. The behavior of the federation tester is correct based on the spec.

**Comment by heini** [comment]
OK, understood. Thanks for clarifying.
