### ISSUE TITLE
Add UI to show server version

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/fed-tester-ui#19]
A bonus would be to warn if you are on an old version of Synapse. Maybe red if <0.99.0 and yellow if <0.99.3. I don't know if there is any way to automate checking which version is current or if you just have to hard code it.

**Comment by turt2live** [comment]
unless it wasn't deployed. I think this is possible as of 8 hours ago: https://github.com/matrix-org/fed-tester-ui/pull/16
