### ISSUE TITLE
more security checks

### ISSUE THREAD

**Issue by vince2010091** [matrix-org/fed-tester-ui#28]
Hello, 

It would be a good point to implement more security checks, for exemple SSL ciphers or TLS1.0/1.1 presence, separate domains, headers, CSP and so on...

Regards,
Vince

**Comment by richvdh** [comment]
Extra checks would need to be implemented in the backend before the frontend, so https://github.com/matrix-org/matrix-federation-tester is a better place to file such issues.

It would probably be also be better if you could open separate issues for each suggestion and give more details for each one, why it would be beneficial for the federation tester to check it. For example, I have no idea what you mean by "separate domains".

Some of the things you suggest already have related open issues (such as https://github.com/matrix-org/matrix-federation-tester/issues/110 and https://github.com/matrix-org/matrix-federation-tester/issues/90) so do search for existing open issues before opening new ones.

**Comment by vince2010091** [comment]
Regarding separate domains: 
https://github.com/vector-im/element-web/#important-security-notes
https://github.com/matrix-org/synapse#security-note
