### ISSUE TITLE
Broken link in 'WARN: Could not find a valid certificate. See this documentation for instructions on how to fix this.'

### ISSUE THREAD

**Issue by notshriram** [matrix-org/fed-tester-ui#30]
**Describe the bug**
Link to documentation broken in the Warning that arises with `x509: certificate is not valid for any names, but wanted to match matrix.example.com`

**To Reproduce**
1. Go to [federation tester](https://federationtester.matrix.org/)
2. enter a server url which does not have valid certificates
3. See error message explaining the valid certificates error. See error message explaining the valid certificates error
4. Click on the "[this documentation](https://github.com/matrix-org/synapse/blob/master/docs/MSC1711_certificates_FAQ.md#configuring-certificates-for-compatibility-with-synapse-100)" link in the WARN: message

**Expected behavior**
should link to the relevant documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/49370927/162146236-7243818d-2fe0-40ba-b271-65989207a8f4.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Browser safari
 - Version 15.4

**Comment by richvdh** [comment]
dup #29
